- name: Deploy GitHub Dashboard
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure project is present
      ansible.builtin.git:
        repo: https://github.com/RakshitYadav09/github-dashboard.git
        dest: ./github-dashboard
        clone: yes
      ignore_errors: true

    - name: Build and start containers
      community.docker.docker_compose:
        project_src: ./github-dashboard
        state: present
